name: WPS每日签到(7:00)

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: 缓存Node依赖
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm

      - name: 缓存Playwright浏览器
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-pw

      - name: 安装Node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: 安装依赖
        run: npm install

      - name: 安装浏览器
        run: npx playwright install chromium --with-deps

      # 👇 这一步把 Secrets 里的内容写入 state.json
      - name: 生成state.json
        env:
          STATE_JSON: ${{ secrets.STATE_JSON }}
        run: echo "$STATE_JSON" > state.json

      - name: 执行签到
        run: node sign.js
